# Generated by Django 4.2.16 on 2024-10-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_rename_ratings_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-timestamp']},
        ),
    ]
